//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUS.REGON.Models.Descriptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Response {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Response() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUS.REGON.Models.Descriptions.Response", typeof(Response).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniwersalna klasa reprezentująca element słownikowy systemu REGON. Składa się z unikalnego identyfikatora (kodu) oraz odpowiadającej mu nazwy opisowej, zgodnie z klasyfikacjami GUS. / A universal class representing a dictionary item of the REGON system. It consists of a unique identifier (code) and a corresponding descriptive name, according to GUS classifications..
        /// </summary>
        public static string DictionaryItem {
            get {
                return ResourceManager.GetString("DictionaryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucz słownikowy (kod) identyfikujący daną pozycję w konkretnej klasyfikacji (np. &apos;62.01.Z&apos; dla PKD lub &apos;14&apos; dla województwa mazowieckiego). / Dictionary key (code) identifying a given position in a specific classification (e.g., &apos;62.01.Z&apos; for PKD or &apos;14&apos; for the Masovian Voivodeship)..
        /// </summary>
        public static string DictionaryItem_Code {
            get {
                return ResourceManager.GetString("DictionaryItem_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pełna nazwa opisowa przypisana do danego kodu w rejestrach urzędowych. / Full descriptive name assigned to a given code in official registers..
        /// </summary>
        public static string DictionaryItem_Nazwa {
            get {
                return ResourceManager.GetString("DictionaryItem_Nazwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa reprezentująca pełny raport z systemu REGON dla danego podmiotu. Agreguje dane o statusie odpowiedzi, szczegółowe informacje o instytucji oraz klasyfikację PKD. / The class representing a full REGON report for a given entity. It aggregates data on response status, detailed institution information, and PKD classification..
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Właściwość pomocnicza (techniczna) określająca, czy raport zawiera kompletne dane merytoryczne. Zwraca &apos;true&apos; tylko dla statusu &apos;Istnieje&apos;, co gwarantuje dostępność obiektów Institution oraz Pkd. / A technical helper property determining if the report contains complete substantive data. Returns &apos;true&apos; only for the &apos;Exists&apos; status, guaranteeing the availability of Institution and Pkd objects..
        /// </summary>
        public static string Full_HasValue {
            get {
                return ResourceManager.GetString("Full_HasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegółowe dane identyfikacyjne i adresowe podmiotu (np. nazwa, NIP, adres siedziby). Pole niepuste tylko w przypadku odnalezienia aktywnych danych. / Detailed identification and address data of the entity (e.g., name, NIP, registered office address). Field is non-null only when active data is found..
        /// </summary>
        public static string Full_Institution {
            get {
                return ResourceManager.GetString("Full_Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zestawienie kodów Polskiej Klasyfikacji Działalności przypisanych do podmiotu w rejestrze urzędowym. / A list of Polish Classification of Activities (PKD) codes assigned to the entity in the official register..
        /// </summary>
        public static string Full_Pkd {
            get {
                return ResourceManager.GetString("Full_Pkd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status wyniku zapytania do bazy BIR (Baza Internetowa REGON). Informuje, czy podmiot został odnaleziony, czy wystąpił brak uprawnień lub inne zdarzenie systemowe. / The status of the BIR database (REGON Internet Database) query result. Informs whether the entity was found, if there was a lack of permissions, or another system event..
        /// </summary>
        public static string Full_Status {
            get {
                return ResourceManager.GetString("Full_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa zawierająca szczegółowe dane instytucjonalne podmiotu gospodarki narodowej, obejmujące informacje adresowe oraz kluczowe daty dotyczące cyklu życia jednostki w rejestrze REGON. / The class containing detailed institutional data of a national economy entity, including address information and key dates regarding the entity&apos;s life cycle in the REGON register..
        /// </summary>
        public static string Institution {
            get {
                return ResourceManager.GetString("Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane o siedzibie podmiotu lub miejscu prowadzenia działalności. Struktura oparta jest na hierarchicznym podziale terytorialnym kraju (TERYT). / Data about the entity&apos;s registered office or place of business. The structure is based on the hierarchical territorial division of the country (TERYT)..
        /// </summary>
        public static string Institution_Address {
            get {
                return ResourceManager.GetString("Institution_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka podziału terytorialnego stopnia gminnego. / Municipality-level territorial division unit..
        /// </summary>
        public static string Institution_Address_Gmina {
            get {
                return ResourceManager.GetString("Institution_Address_Gmina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy przypisany do adresu siedziby. / Postcode assigned to the registered office address..
        /// </summary>
        public static string Institution_Address_KodPocztowy {
            get {
                return ResourceManager.GetString("Institution_Address_KodPocztowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod i nazwa kraju siedziby podmiotu. / Code and name of the country of the entity&apos;s registered office..
        /// </summary>
        public static string Institution_Address_Kraj {
            get {
                return ResourceManager.GetString("Institution_Address_Kraj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa miejscowości siedziby podmiotu zgodna z rejestrem TERYT. / Name of the entity&apos;s seat locality according to the TERYT register..
        /// </summary>
        public static string Institution_Address_Miejscowosc {
            get {
                return ResourceManager.GetString("Institution_Address_Miejscowosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa miejscowości, w której znajduje się urząd pocztowy właściwy dla adresu. / Name of the town where the post office appropriate for the address is located..
        /// </summary>
        public static string Institution_Address_MiejscowoscPoczty {
            get {
                return ResourceManager.GetString("Institution_Address_MiejscowoscPoczty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatkowy opis lokalizacji dla miejsc niestandardowych (np. &quot;skrytka pocztowa&quot;, &quot;peron&quot;). / Additional location description for non-standard places (e.g., &quot;PO box&quot;, &quot;platform&quot;)..
        /// </summary>
        public static string Institution_Address_NietypoweMiejsceLokalizacji {
            get {
                return ResourceManager.GetString("Institution_Address_NietypoweMiejsceLokalizacji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer lokalu mieszkalnego lub użytkowego w obrębie nieruchomości. / Apartment or business premises number within the real estate..
        /// </summary>
        public static string Institution_Address_NumerLokalu {
            get {
                return ResourceManager.GetString("Institution_Address_NumerLokalu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer porządkowy nieruchomości (budynku). / Real estate (building) reference number..
        /// </summary>
        public static string Institution_Address_NumerNieruchomosci {
            get {
                return ResourceManager.GetString("Institution_Address_NumerNieruchomosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka podziału terytorialnego stopnia powiatowego. / County-level territorial division unit..
        /// </summary>
        public static string Institution_Address_Powiat {
            get {
                return ResourceManager.GetString("Institution_Address_Powiat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa ulicy (jeśli występuje w danej miejscowości) wraz z kodem z katalogu ulic ULIC. / Street name (if applicable) with a code from the ULIC street catalogue..
        /// </summary>
        public static string Institution_Address_Ulica {
            get {
                return ResourceManager.GetString("Institution_Address_Ulica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jednostka podziału terytorialnego stopnia wojewódzkiego. / Voivodeship-level territorial division unit..
        /// </summary>
        public static string Institution_Address_Wojewodztwo {
            get {
                return ResourceManager.GetString("Institution_Address_Wojewodztwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struktura danych adresowych określająca fizyczną lokalizację siedziby podmiotu. Obejmuje pełną hierarchię terytorialną (kraj, województwo, powiat, gmina, miejscowość) oraz szczegółowe dane punktu adresowego (ulica, numer nieruchomości i lokalu) zgodnie z rejestrem TERYT. / Address data structure specifying the physical location of the entity&apos;s registered office. It includes the full territorial hierarchy (country, voivodeship, county, municipality, locality) and detailed address point data (street, property [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Institution_Adres {
            get {
                return ResourceManager.GetString("Institution_Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zbiór dat dokumentujących historię rejestrową podmiotu, od momentu powstania do ewentualnego skreślenia z rejestru. / A set of dates documenting the entity&apos;s registration history, from the moment of formation to possible removal from the register..
        /// </summary>
        public static string Institution_Dates {
            get {
                return ResourceManager.GetString("Institution_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data faktycznego powstania podmiotu (np. data podpisania aktu notarialnego). / The date of the entity&apos;s actual formation..
        /// </summary>
        public static string Institution_Dates_DataPowstania {
            get {
                return ResourceManager.GetString("Institution_Dates_DataPowstania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data rozpoczęcia działalności gospodarczej lub statutowej. / The date of commencement of economic or statutory activity..
        /// </summary>
        public static string Institution_Dates_DataRozpoczecia {
            get {
                return ResourceManager.GetString("Institution_Dates_DataRozpoczecia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wykreślenia podmiotu z krajowego rejestru urzędowego REGON. / The date of removal of the entity from the REGON national official register..
        /// </summary>
        public static string Institution_Dates_DataSkreslenia {
            get {
                return ResourceManager.GetString("Institution_Dates_DataSkreslenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data dokonania wpisu podmiotu do rejestru REGON. / The date the entity was entered into the REGON register..
        /// </summary>
        public static string Institution_Dates_DataWpisu {
            get {
                return ResourceManager.GetString("Institution_Dates_DataWpisu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wpisu do rejestru macierzystego (np. KRS, CEIDG lub innego rejestru branżowego). / The date of entry in the parent register (e.g., KRS, CEIDG, or another industry register)..
        /// </summary>
        public static string Institution_Dates_DataWpisuDoRejestruEwidencji {
            get {
                return ResourceManager.GetString("Institution_Dates_DataWpisuDoRejestruEwidencji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data powrotu do aktywnego wykonywania działalności po okresie zawieszenia. / The date of resumption of active activity after a period of suspension..
        /// </summary>
        public static string Institution_Dates_DataWznowienia {
            get {
                return ResourceManager.GetString("Institution_Dates_DataWznowienia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data faktycznego zakończenia działalności przez podmiot. / The date of actual termination of activity by the entity..
        /// </summary>
        public static string Institution_Dates_DataZakonczenia {
            get {
                return ResourceManager.GetString("Institution_Dates_DataZakonczenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data czasowego zaprzestania wykonywania działalności. / The date of temporary suspension of activity..
        /// </summary>
        public static string Institution_Dates_DataZawieszenia {
            get {
                return ResourceManager.GetString("Institution_Dates_DataZawieszenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data ostatniej istotnej aktualizacji danych podmiotu w rejestrze. / The date of the last significant update of the entity&apos;s data in the register..
        /// </summary>
        public static string Institution_Dates_DataZmiany {
            get {
                return ResourceManager.GetString("Institution_Dates_DataZmiany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zestaw kluczowych dat dotyczących cyklu życia podmiotu w rejestrach państwowych. / A set of key dates regarding the entity&apos;s life cycle in state registers..
        /// </summary>
        public static string Institution_Daty {
            get {
                return ResourceManager.GetString("Institution_Daty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opisowe zestawienie rodzajów działalności lub dodatkowe informacje o profilu jednostki. / Descriptive summary of activities or additional information about the entity&apos;s profile..
        /// </summary>
        public static string Institution_Dzialalnosci {
            get {
                return ResourceManager.GetString("Institution_Dzialalnosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Określenie sposobu finansowania działalności podmiotu (np. jednostka budżetowa, samofinansowanie). / Specification of the entity&apos;s financing method (e.g., budgetary unit)..
        /// </summary>
        public static string Institution_FormaFinansowania {
            get {
                return ResourceManager.GetString("Institution_FormaFinansowania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struktura własnościowa podmiotu (np. własność prywatna krajowa, własność skarbu państwa, własność zagraniczna). / The ownership structure of the entity (e.g., domestic private ownership, state treasury ownership)..
        /// </summary>
        public static string Institution_FormaWlasnosci {
            get {
                return ResourceManager.GetString("Institution_FormaWlasnosci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pełna nazwa podmiotu gospodarki narodowej zarejestrowana w systemie REGON. / Full name of the national economy entity registered in the REGON system..
        /// </summary>
        public static string Institution_Nazwa {
            get {
                return ResourceManager.GetString("Institution_Nazwa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrócona nazwa podmiotu (jeśli została zgłoszona i występuje w rejestrze). / Shortened name of the entity (if provided and present in the register)..
        /// </summary>
        public static string Institution_NazwaSkrocona {
            get {
                return ResourceManager.GetString("Institution_NazwaSkrocona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer, pod którym podmiot widnieje w swoim rejestrze macierzystym (np. numer KRS dla spółek, numer w ewidencji szkół, itp.). / The number under which the entity is listed in its primary register (e.g., KRS number for companies)..
        /// </summary>
        public static string Institution_NumerwRejestrzeEwidencji {
            get {
                return ResourceManager.GetString("Institution_NumerwRejestrzeEwidencji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownikowy opis organu, który dokonał wpisu podmiotu do rejestru macierzystego (np. Sąd Rejonowy, Ministerstwo). / Dictionary description of the body that entered the entity into the primary register..
        /// </summary>
        public static string Institution_OrganRejestrowy {
            get {
                return ResourceManager.GetString("Institution_OrganRejestrowy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podmiot lub organ, który utworzył daną jednostkę (często występuje przy jednostkach budżetowych lub publicznych). / The entity or body that created the unit..
        /// </summary>
        public static string Institution_OrganZalozycielski {
            get {
                return ResourceManager.GetString("Institution_OrganZalozycielski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Główna kategoryzacja prawna podmiotu (np. osoba prawna, jednostka organizacyjna niemająca osobowości prawnej). / The main legal categorization of the entity..
        /// </summary>
        public static string Institution_PodstawowaFormaPrawna {
            get {
                return ResourceManager.GetString("Institution_PodstawowaFormaPrawna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer identyfikacyjny REGON (Krajowy Rejestr Urzędowy Podmiotów Gospodarki Narodowej). W zależności od typu jednostki może być 9-cyfrowy lub 14-cyfrowy (dla jednostek lokalnych). / REGON identification number. Depending on the entity type, it can be 9 or 14 digits long..
        /// </summary>
        public static string Institution_Regon {
            get {
                return ResourceManager.GetString("Institution_Regon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ rejestru lub ewidencji, w której podmiot jest zarejestrowany poza systemem REGON. / Type of register or record in which the entity is registered outside the REGON system..
        /// </summary>
        public static string Institution_RodzajRejestru {
            get {
                return ResourceManager.GetString("Institution_RodzajRejestru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uszczegółowienie formy prawnej (np. spółka z ograniczoną odpowiedzialnością, fundacja, stowarzyszenie). / Specific legal form (e.g., limited liability company, foundation)..
        /// </summary>
        public static string Institution_SzczegolnaFormaPrawna {
            get {
                return ResourceManager.GetString("Institution_SzczegolnaFormaPrawna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasyfikacja słownikowa określająca typ strukturalny jednostki w rejestrze REGON (np. jednostka prawna, jednostka lokalna). Pozwala na identyfikację stopnia samodzielności i roli podmiotu w strukturze gospodarczej kraju. / Dictionary classification specifying the structural type of the entity in the REGON register (e.g., legal entity, local unit). It allows for identification of the autonomy degree and the entity&apos;s role in the country&apos;s economic structure..
        /// </summary>
        public static string Institution_TypJednostki {
            get {
                return ResourceManager.GetString("Institution_TypJednostki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa reprezentuje zestawienie rodzajów działalności jednostki według Polskiej Klasyfikacji Działalności (PKD). Zawiera listę wpisów określających przeważający oraz poboczne kody działalności zarejestrowane w rejestrze REGON. / The class represents a set of entity activity types according to the Polish Classification of Activities (PKD). It includes a list of entries specifying the primary and secondary activity codes registered in the REGON register..
        /// </summary>
        public static string Pkd {
            get {
                return ResourceManager.GetString("Pkd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa opisująca pojedynczy wpis w rejestrze działalności. Przechowuje informacje o konkretnym kodzie PKD oraz informację, czy stanowi on przeważający rodzaj działalności. / A class describing a single entry in the activity register. It stores information about a specific PKD code and whether it constitutes the predominant type of activity..
        /// </summary>
        public static string Pkd_Item {
            get {
                return ResourceManager.GetString("Pkd_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znacznik określający przeważający rodzaj działalności. Wartość &apos;true&apos; oznacza działalność przeważającą (kod główny), wartość &apos;false&apos; oznacza działalność pozostałą. / Marker specifying the predominant type of activity. A value of &apos;true&apos; indicates the predominant activity (main code), a value of &apos;false&apos; indicates other activities..
        /// </summary>
        public static string Pkd_Item_IsMain {
            get {
                return ResourceManager.GetString("Pkd_Item_IsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegółowy kod PKD wraz z opisem (element słownikowy). Odpowiada wartościom z oficjalnego słownika Głównego Urzędu Statystycznego. / Detailed PKD code with a description (dictionary item). Corresponds to the values from the official dictionary of the Statistics Poland (GUS)..
        /// </summary>
        public static string Pkd_Item_Pkd {
            get {
                return ResourceManager.GetString("Pkd_Item_Pkd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolekcja poszczególnych wpisów klasyfikacji PKD przypisanych do podmiotu. / Collection of individual PKD classification entries assigned to the entity..
        /// </summary>
        public static string Pkd_Items {
            get {
                return ResourceManager.GetString("Pkd_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja o bieżącym czasie systemowym serwera. Używana do synchronizacji czasu między klientem a serwerem. / Information about the current system time of the server. Used for time synchronization between the client and the server..
        /// </summary>
        public static string ServerTimeResponse {
            get {
                return ResourceManager.GetString("ServerTimeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bieżąca data i godzina serwera wraz z przesunięciem czasowym (ISO 8601). / Current server date and time with time zone offset (ISO 8601)..
        /// </summary>
        public static string ServerTimeResponse_CurrentDateTime {
            get {
                return ResourceManager.GetString("ServerTimeResponse_CurrentDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak uprawnień do raportu. .
        /// </summary>
        public static string Status_BrakUprawnien {
            get {
                return ResourceManager.GetString("Status_BrakUprawnien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znaleziono podmioty. .
        /// </summary>
        public static string Status_Istneje {
            get {
                return ResourceManager.GetString("Status_Istneje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono podmiotów. .
        /// </summary>
        public static string Status_NieIstneje {
            get {
                return ResourceManager.GetString("Status_NieIstneje", resourceCulture);
            }
        }
    }
}
