//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RADON {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RADON.Dictionary", typeof(Dictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz status kierunku na podstawie kodu słownikowego / Get course status name by unique code..
        /// </summary>
        public static string course_current_statuses {
            get {
                return ResourceManager.GetString("course_current_statuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz formy kształcenia / Get course instance form names..
        /// </summary>
        public static string course_instance_forms {
            get {
                return ResourceManager.GetString("course_instance_forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz statusy uruchomienia / Get course instance status names..
        /// </summary>
        public static string course_instance_statuses {
            get {
                return ResourceManager.GetString("course_instance_statuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz rodzaje podstawy prawnej / Get legal basis type names..
        /// </summary>
        public static string course_legal_basis_types {
            get {
                return ResourceManager.GetString("course_legal_basis_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz poziomy / Get course levels names..
        /// </summary>
        public static string course_levels {
            get {
                return ResourceManager.GetString("course_levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz rodzaje instytucji głównych / Get main institution kinds..
        /// </summary>
        public static string course_main_institution_kinds {
            get {
                return ResourceManager.GetString("course_main_institution_kinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz języki (filologii obcej lub kształcenia) / Get languages names (Language of philology or languages of education)..
        /// </summary>
        public static string course_philological_languages {
            get {
                return ResourceManager.GetString("course_philological_languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz tytuły zawodowe / Get professional title names..
        /// </summary>
        public static string course_professional_titles {
            get {
                return ResourceManager.GetString("course_professional_titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz profile kształcenia / Get course profiles..
        /// </summary>
        public static string course_profiles {
            get {
                return ResourceManager.GetString("course_profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz rodzaje instytucji / Get institution kind names..
        /// </summary>
        public static string institution_kinds {
            get {
                return ResourceManager.GetString("institution_kinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz typy instytucji naukowych / Get scientific institution types names..
        /// </summary>
        public static string institution_scientific_institution_types {
            get {
                return ResourceManager.GetString("institution_scientific_institution_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz statusy instytucji / Get status names..
        /// </summary>
        public static string institution_statuses {
            get {
                return ResourceManager.GetString("institution_statuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz typy uczelni / Get university types names..
        /// </summary>
        public static string institution_university_types {
            get {
                return ResourceManager.GetString("institution_university_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz wszystkie dostępne dyscypliny / Get disciplines names..
        /// </summary>
        public static string shared_disciplines {
            get {
                return ResourceManager.GetString("shared_disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz wszystkie dostępne dziedziny / Get domains names..
        /// </summary>
        public static string shared_domains {
            get {
                return ResourceManager.GetString("shared_domains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz wszystkie dostępne instytucje nadzorujące / Get supervising institutions.
        /// </summary>
        public static string shared_supervising_institutions {
            get {
                return ResourceManager.GetString("shared_supervising_institutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz wszystkie dostępne województwa / Get voivodeship names..
        /// </summary>
        public static string shared_voivodeships {
            get {
                return ResourceManager.GetString("shared_voivodeships", resourceCulture);
            }
        }
    }
}
