//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RADON.Models.Descriptions.Institutions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QueryParameter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryParameter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RADON.Models.Descriptions.Institutions.QueryParameter", typeof(QueryParameter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa odpowiada za definiowanie kryteriów filtrowania, sortowania oraz identyfikacji instytucji w zapytaniach typu GET. Służy jako most pomiędzy parametrami przekazanymi w adresie URL a logiką wyszukiwania w bazie danych. / The class is responsible for defining filtering, sorting, and identification criteria for institutions in GET requests. It acts as a bridge between URL query parameters and database search logic..
        /// </summary>
        public static string QueryParameters {
            get {
                return ResourceManager.GetString("QueryParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikatory instytucji - tablica uuid instytucji z POL-on 2.0. / Array of institution identifiers - POL-on 2.0 system uuids..
        /// </summary>
        public static string QueryParameters_InstitutionUuids {
            get {
                return ResourceManager.GetString("QueryParameters_InstitutionUuids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj instytucji - tablica kodów słownikowych. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji. / Array of codes of institution kinds. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string QueryParameters_KindCodes {
            get {
                return ResourceManager.GetString("QueryParameters_KindCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer KRS - Krajowy Rejestr Sądowy. / National Court Register number (KRS number)..
        /// </summary>
        public static string QueryParameters_Krs {
            get {
                return ResourceManager.GetString("QueryParameters_Krs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa instytucji (może być fragmentem nazwy). / Name of institution (can be a partial name)..
        /// </summary>
        public static string QueryParameters_Name {
            get {
                return ResourceManager.GetString("QueryParameters_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP - Numer Identyfikacji Podatkowej. / Tax Identification Number (NIP)..
        /// </summary>
        public static string QueryParameters_Nip {
            get {
                return ResourceManager.GetString("QueryParameters_Nip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer REGON instytucji. / REGON of institution..
        /// </summary>
        public static string QueryParameters_Regon {
            get {
                return ResourceManager.GetString("QueryParameters_Regon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ instytucji naukowej - tablica kodów słownikowych. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji. / Array of codes of scientific institution types. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string QueryParameters_ScientificInstitutionTypeCodes {
            get {
                return ResourceManager.GetString("QueryParameters_ScientificInstitutionTypeCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status instytucji - tablica kodów słownikowych. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji. / Array of codes of institution statuses. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string QueryParameters_StatusCodes {
            get {
                return ResourceManager.GetString("QueryParameters_StatusCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ uczelni - tablica kodów słownikowych. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji. / Array of codes of university types. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string QueryParameters_UniversityTypeCodes {
            get {
                return ResourceManager.GetString("QueryParameters_UniversityTypeCodes", resourceCulture);
            }
        }
    }
}
