//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RADON.Models.Descriptions.Institutions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Response {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Response() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RADON.Models.Descriptions.Institutions.Response", typeof(Response).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa reprezentuje pełny zestaw danych o instytucji (np. uczelni, instytucie naukowym), uwzględniając jej identyfikatory, historię zmian (migawki/snapshots) oraz dane teleadresowe. / The class represents a complete set of data about an institution (e.g., university, scientific institute), including its identifiers, history of changes (snapshots), and contact details..
        /// </summary>
        public static string Institution {
            get {
                return ResourceManager.GetString("Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja o źródle danych (np. nazwa systemu zewnętrznego). / Information about data source..
        /// </summary>
        public static string Institution_DataSource {
            get {
                return ResourceManager.GetString("Institution_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres e-mail. / E-mail address..
        /// </summary>
        public static string Institution_Email {
            get {
                return ResourceManager.GetString("Institution_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj instytucji - kod i nazwa słownikowa. / Institution kind - dictionary code and name..
        /// </summary>
        public static string Institution_InstitutionKind {
            get {
                return ResourceManager.GetString("Institution_InstitutionKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator instytucji - uuid instytucji z systemu POL-on 2.0. / Institution identifier - POL-on 2.0 system uuid..
        /// </summary>
        public static string Institution_InstitutionUuid {
            get {
                return ResourceManager.GetString("Institution_InstitutionUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer KRS / National Court Register number (KRS number)..
        /// </summary>
        public static string Institution_Krs {
            get {
                return ResourceManager.GetString("Institution_Krs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja o czasie ostatniego odświeżania danych w lokalnym systemie. / Information about the last data refresh time in the local system..
        /// </summary>
        public static string Institution_LastRefresh {
            get {
                return ResourceManager.GetString("Institution_LastRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data likwidacji (jeśli dotyczy). / Institution liquidation date..
        /// </summary>
        public static string Institution_LiquidationDate {
            get {
                return ResourceManager.GetString("Institution_LiquidationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data postawienia w stan likwidacji (jeśli dotyczy). / Institution liquidation start date..
        /// </summary>
        public static string Institution_LiquidationStartDate {
            get {
                return ResourceManager.GetString("Institution_LiquidationStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia zmian nazw instytucji (kolekcja migawek). / History of institution name changes (collection of snapshots)..
        /// </summary>
        public static string Institution_Names {
            get {
                return ResourceManager.GetString("Institution_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP / Tax Identification Number (NIP)..
        /// </summary>
        public static string Institution_Nip {
            get {
                return ResourceManager.GetString("Institution_Nip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu. / Phone number..
        /// </summary>
        public static string Institution_Phone {
            get {
                return ResourceManager.GetString("Institution_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON instytucji. / Institution REGON..
        /// </summary>
        public static string Institution_Regon {
            get {
                return ResourceManager.GetString("Institution_Regon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas ostatniego odświeżania danych w systemie źródłowym (POL-on). / Last refresh time in the source system (POL-on)..
        /// </summary>
        public static string Institution_SourceLastRefresh {
            get {
                return ResourceManager.GetString("Institution_SourceLastRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data utworzenia instytucji. / Institution creation date..
        /// </summary>
        public static string Institution_StartDate {
            get {
                return ResourceManager.GetString("Institution_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia zmian statusu instytucji (kolekcja migawek). / History of institution status changes (collection of snapshots)..
        /// </summary>
        public static string Institution_Statuses {
            get {
                return ResourceManager.GetString("Institution_Statuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia zmian typu instytucji (kolekcja migawek). / History of institution type changes (collection of snapshots)..
        /// </summary>
        public static string Institution_Types {
            get {
                return ResourceManager.GetString("Institution_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres strony WWW. / Web address..
        /// </summary>
        public static string Institution_Www {
            get {
                return ResourceManager.GetString("Institution_Www", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migawka nazwy instytucji. Przechowuje nazwę obowiązującą w konkretnym przedziale czasowym. / Institution name snapshot. Stores the name valid within a specific time range..
        /// </summary>
        public static string NameSnapshot {
            get {
                return ResourceManager.GetString("NameSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa instytucji obowiązująca od wskazanej daty. / Institution name valid from the specified date..
        /// </summary>
        public static string NameSnapshot_Date {
            get {
                return ResourceManager.GetString("NameSnapshot_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data, od której dana nazwa zaczęła obowiązywać w systemie. / The date from which the specific name became effective in the system..
        /// </summary>
        public static string NameSnapshot_Name {
            get {
                return ResourceManager.GetString("NameSnapshot_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migawka statusu instytucji. Informuje o stanie prawnym (np. aktywna, w likwidacji) w danym czasie. / Institution status snapshot. Informs about the legal status at a given time..
        /// </summary>
        public static string StatusSnapshot {
            get {
                return ResourceManager.GetString("StatusSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wystąpienia lub aktualizacji danego statusu. / The date of occurrence or update of the given status..
        /// </summary>
        public static string StatusSnapshot_Date {
            get {
                return ResourceManager.GetString("StatusSnapshot_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stan formalno-prawny instytucji (np. aktywna, w likwidacji, zlikwidowana) – obiekt słownikowy. / Formal and legal status of the institution (e.g., active, in liquidation, liquidated) – dictionary object..
        /// </summary>
        public static string StatusSnapshot_Status {
            get {
                return ResourceManager.GetString("StatusSnapshot_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migawka typu instytucji. Określa rodzaj działalności (np. uczelnia publiczna) w danym czasie. / Institution type snapshot. Defines the type of activity at a given time..
        /// </summary>
        public static string TypeSnapshot {
            get {
                return ResourceManager.GetString("TypeSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data nadania lub zmiany typu instytucji. / The date of assignment or change of the institution type..
        /// </summary>
        public static string TypeSnapshot_Date {
            get {
                return ResourceManager.GetString("TypeSnapshot_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj/typ instytucji (np. uczelnia publiczna, instytut badawczy) – obiekt słownikowy zawierający kod i nazwę. / Institution type (e.g., public university, research institute) – dictionary object containing code and name..
        /// </summary>
        public static string TypeSnapshot_Type {
            get {
                return ResourceManager.GetString("TypeSnapshot_Type", resourceCulture);
            }
        }
    }
}
