using Diploma.Application.Interfaces.Generators;

namespace Diploma.Application.Persons.Commands.Authentication.MessageGenerators;

public sealed record PersonLoginInSuccessMessageInput : MessageGeneratorInput;
public interface IPersonLoginInSuccessMessageGenerator : IMessageGenerator<PersonLoginInSuccessMessageInput>;