//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RADON.Contracts.Descriptions.Courses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QueryParameter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryParameter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RADON.Contracts.Descriptions.Courses.QueryParameter", typeof(QueryParameter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy studia pomostowe? / Bridging course marker?.
        /// </summary>
        public static string course_bridging_description {
            get {
                return ResourceManager.GetString("course_bridging_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy instytucja współprowadząca jest zagraniczna? / Is the co-leading institution foreign?.
        /// </summary>
        public static string course_co_leading_institution_is_foreign_description {
            get {
                return ResourceManager.GetString("course_co_leading_institution_is_foreign_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa instytucji współprowadzącej studia na kierunku / Co-leading institution name..
        /// </summary>
        public static string course_co_leading_institution_name_description {
            get {
                return ResourceManager.GetString("course_co_leading_institution_name_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator instytucji współprowadzącej studia na kierunku - uuid instytucji z POL-on 2.0 / Co-leading institution identifier - POL-on 2 system uuid..
        /// </summary>
        public static string course_co_leading_institution_uuid_description {
            get {
                return ResourceManager.GetString("course_co_leading_institution_uuid_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy studia wspólne? / Co led course marker?.
        /// </summary>
        public static string course_co_led_description {
            get {
                return ResourceManager.GetString("course_co_led_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy studia we współpracy z organizacją zawodową? / Cooperation with vocational marker?.
        /// </summary>
        public static string course_coop_with_vocational_description {
            get {
                return ResourceManager.GetString("course_coop_with_vocational_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod kierunku / Course code..
        /// </summary>
        public static string course_course_code_description {
            get {
                return ResourceManager.GetString("course_course_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod uruchomienia / Course instance code..
        /// </summary>
        public static string course_course_instance_code_description {
            get {
                return ResourceManager.GetString("course_course_instance_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator uruchomienia - uuid z POL-on 2.0 / Course instance identifier - POL-on 2 system uuid..
        /// </summary>
        public static string course_course_instance_uuid_description {
            get {
                return ResourceManager.GetString("course_course_instance_uuid_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa kierunku / Course name..
        /// </summary>
        public static string course_course_name_description {
            get {
                return ResourceManager.GetString("course_course_name_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator kierunku - uuid z POL-on 2.0 / Course identifier - POL-on 2 system uuid..
        /// </summary>
        public static string course_course_uuid_description {
            get {
                return ResourceManager.GetString("course_course_uuid_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualny status kierunku studiów - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Current course status code Use dictionary service to receive extended information..
        /// </summary>
        public static string course_current_status_code_description {
            get {
                return ResourceManager.GetString("course_current_status_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod słownikowy dyscypliny. Skorzystaj z usługi Dyscypliny i dziedziny naukowe, aby uzyskać więcej informacji / Discipline code. Use discipline service to receive extended information..
        /// </summary>
        public static string course_discipline_code_description {
            get {
                return ResourceManager.GetString("course_discipline_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa dyscypliny / Discipline name..
        /// </summary>
        public static string course_discipline_name_description {
            get {
                return ResourceManager.GetString("course_discipline_name_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy studia dualne? / Dual course marker?.
        /// </summary>
        public static string course_dual_description {
            get {
                return ResourceManager.GetString("course_dual_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język kształcenia - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Education language code. Use dictionary service to receive extended information..
        /// </summary>
        public static string course_education_language_code_description {
            get {
                return ResourceManager.GetString("course_education_language_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma kształcenia - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Course instance form code. Use dictionary service to receive extended information..
        /// </summary>
        public static string course_form_code_description {
            get {
                return ResourceManager.GetString("course_form_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja o czasie ostatniego odświeżania danych (znacznik czasu - bieżący czas uniksowy w milisekundach) / Information about the last data refresh time (timestamp - current Unix epoch time in milliseconds)..
        /// </summary>
        public static string course_last_refresh_description {
            get {
                return ResourceManager.GetString("course_last_refresh_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto instytucji prowadzącej studia na kierunku (jeśli instytucją prowadzącą jest filia, to jest to miasto z adresu tej filii) / Leading institution city..
        /// </summary>
        public static string course_leading_institution_city_description {
            get {
                return ResourceManager.GetString("course_leading_institution_city_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy instytucja prowadząca jest zagraniczna/ Foreign leading institution marker..
        /// </summary>
        public static string course_leading_institution_is_foreign_description {
            get {
                return ResourceManager.GetString("course_leading_institution_is_foreign_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa instytucji prowadzącej studia na kierunku (instytucją prowadzącą może być instytucja główna lub filia) / Leading institution name..
        /// </summary>
        public static string course_leading_institution_name_description {
            get {
                return ResourceManager.GetString("course_leading_institution_name_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator instytucji prowadzącej studia na kierunku (instytucją prowadzącą może być instytucja główna lub filia) - uuid instytucji z POL-on 2.0 / Leading institution identifier - POL-on 2 system uuid..
        /// </summary>
        public static string course_leading_institution_uuid_description {
            get {
                return ResourceManager.GetString("course_leading_institution_uuid_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Województwo instytucji prowadzącej studia na kierunku (jeśli instytucją prowadzącą jest filia, to jest to województwo z adresu tej filii) - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Leading institution voivodeship code. Use dictionary service to receive extended information..
        /// </summary>
        public static string course_leading_institution_voivodeship_code_description {
            get {
                return ResourceManager.GetString("course_leading_institution_voivodeship_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj podstawy prawnej utworzenia studiów - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Legal basis type code. Use dictionary service to receive extended information..
        /// </summary>
        public static string course_legal_basis_type_code_description {
            get {
                return ResourceManager.GetString("course_legal_basis_type_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poziom - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Course level code. Use dictionary service to receive extended information..
        /// </summary>
        public static string course_level_code_description {
            get {
                return ResourceManager.GetString("course_level_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj instytucji głownej - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Main institution kind - dictionary code. Use dictionary service to receive extended information..
        /// </summary>
        public static string course_main_institution_kind_code_description {
            get {
                return ResourceManager.GetString("course_main_institution_kind_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa instytucji głównej / Main institution name..
        /// </summary>
        public static string course_main_institution_name_description {
            get {
                return ResourceManager.GetString("course_main_institution_name_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator instytucji głównej - uuid instytucji z POL-on 2.0 / Main institution identifier - POL-on 2 system uuid..
        /// </summary>
        public static string course_main_institution_uuid_description {
            get {
                return ResourceManager.GetString("course_main_institution_uuid_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pełna nazwa jednostki organizacyjnej zarządzającej danymi studiów na kierunku (jednostka technicznie przypisana do kierunku) / Organizational unit name (technical field)..
        /// </summary>
        public static string course_organizational_unit_full_name_description {
            get {
                return ResourceManager.GetString("course_organizational_unit_full_name_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator jednostki organizacyjnej zarządzającej danymi studiów na kierunku - uuid z POL-on 2.0 (jednostka technicznie przypisana do kierunku) / Organizational unit identifier - POL-on 2 system uuid..
        /// </summary>
        public static string course_organizational_unit_uuid_description {
            get {
                return ResourceManager.GetString("course_organizational_unit_uuid_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy studia dotyczą filologii obcej? / Philological studies marker?.
        /// </summary>
        public static string course_philological_description {
            get {
                return ResourceManager.GetString("course_philological_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język filologii obcej - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Language code of philology. Use dictionary service to receive extended information..
        /// </summary>
        public static string course_philology_language_code_description {
            get {
                return ResourceManager.GetString("course_philology_language_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil kształcenia - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Course profile code. Use dictionary service to receive extended information..
        /// </summary>
        public static string course_profile_code_description {
            get {
                return ResourceManager.GetString("course_profile_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametr określający liczbę wyników, która ma być zwrócona w odpowiedzi. Domyślna wartość = 10. Maksymalna wartość = 100. / Number of elements to return. Number of results that you want to receive. Default value = 10. Maximum value = 100..
        /// </summary>
        public static string course_result_numbers_description {
            get {
                return ResourceManager.GetString("course_result_numbers_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status uruchomienia - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Course instance status code. Use dictionary service to receive extended information..
        /// </summary>
        public static string course_status_code_description {
            get {
                return ResourceManager.GetString("course_status_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator instytucji nadzorującej dla instytucji głównej - uuid instytucji z POL-on 2.0 / Supervising institution identifier - POL-on 2 system uuid..
        /// </summary>
        public static string course_supervising_institution_uuid_description {
            get {
                return ResourceManager.GetString("course_supervising_institution_uuid_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy studia przygotowują do zawodu nauczyciela / Teacher training marker..
        /// </summary>
        public static string course_teacher_training_description {
            get {
                return ResourceManager.GetString("course_teacher_training_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł zawodowy nadawany absolwentom studiów - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Course professional title code. Use dictionary service to receive extended information..
        /// </summary>
        public static string course_title_code_description {
            get {
                return ResourceManager.GetString("course_title_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Każda poprawna odpowiedź usługi zawiera dane oraz token, który umożliwia pobranie kolejnej partii danych. Przy pierwszym wywołaniu usługi token musi być pustym stringiem. Pobieranie kolejnych stron z wynikami odbywa się z użyciem tokenu, który został zwrócony w poprzedniej odpowiedzi / At the first time the token must be empty string. The new token (after first search) is generated in response and must be forwarded to query if you want to get the next results..
        /// </summary>
        public static string course_token_description {
            get {
                return ResourceManager.GetString("course_token_description", resourceCulture);
            }
        }
    }
}
