//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RADON.Models.Descriptions.Dictionaries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Response {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Response() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RADON.Models.Descriptions.Dictionaries.Response", typeof(Response).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa reprezentuje pojedynczy wpis ze słownika systemowego. Łączy techniczny kod identyfikacyjny z czytelną nazwą wyświetlaną. / The class represents a single entry from the system dictionary. It combines a technical identification code with a readable display name..
        /// </summary>
        public static string DictionaryItem {
            get {
                return ResourceManager.GetString("DictionaryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unikalny kod słownikowy identyfikujący dany element. Wykorzystywany w parametrach filtrowania zapytań. / A unique dictionary code identifying the element. Used in query filtering parameters..
        /// </summary>
        public static string DictionaryItem_Code {
            get {
                return ResourceManager.GetString("DictionaryItem_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pełna nazwa elementu słownika w danym języku (np. nazwa statusu lub typu instytucji). / Full name of the dictionary item in a given language (e.g., name of status or institution type)..
        /// </summary>
        public static string DictionaryItem_Name {
            get {
                return ResourceManager.GetString("DictionaryItem_Name", resourceCulture);
            }
        }
    }
}
