//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUS.TERYT.Models.Requests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUS.TERYT.Models.Requests.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmina ma format 00.00.000.
        /// </summary>
        internal static string GminaIdDescription {
            get {
                return ResourceManager.GetString("GminaIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gmina ma format 00.00.000.
        /// </summary>
        internal static string GminaIdErrorMessage {
            get {
                return ResourceManager.GetString("GminaIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GminaType ma format 0.
        /// </summary>
        internal static string GminaTypeIdDescription {
            get {
                return ResourceManager.GetString("GminaTypeIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GminaType ma format 0.
        /// </summary>
        internal static string GminaTypeIdErrorMessage {
            get {
                return ResourceManager.GetString("GminaTypeIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejscowosc ma format 0000000.
        /// </summary>
        internal static string MiejscowoscIdDescription {
            get {
                return ResourceManager.GetString("MiejscowoscIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejscowosc ma format 0000000.
        /// </summary>
        internal static string MiejscowoscIdErrorMessage {
            get {
                return ResourceManager.GetString("MiejscowoscIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiejscowoscTypeId ma format 00.
        /// </summary>
        internal static string MiejscowoscTypeIdDescription {
            get {
                return ResourceManager.GetString("MiejscowoscTypeIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiejscowoscTypeId ma format 00.
        /// </summary>
        internal static string MiejscowoscTypeIdErrorMessage {
            get {
                return ResourceManager.GetString("MiejscowoscTypeIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiat ma format 00.00.
        /// </summary>
        internal static string PowiatIdDescription {
            get {
                return ResourceManager.GetString("PowiatIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powiat ma format 00.00.
        /// </summary>
        internal static string PowiatIdErrorMessage {
            get {
                return ResourceManager.GetString("PowiatIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica ma format 00000.
        /// </summary>
        internal static string UlicaIdDescription {
            get {
                return ResourceManager.GetString("UlicaIdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica ma format 00000.
        /// </summary>
        internal static string UlicaIdErrorMessage {
            get {
                return ResourceManager.GetString("UlicaIdErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieznany typ.
        /// </summary>
        internal static string UnknownType {
            get {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wojewodztwo ma format 00.
        /// </summary>
        internal static string WojewodztwoIdDecription {
            get {
                return ResourceManager.GetString("WojewodztwoIdDecription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wojewodztwo ma format 00.
        /// </summary>
        internal static string WojewodztwoIdErrorMessage {
            get {
                return ResourceManager.GetString("WojewodztwoIdErrorMessage", resourceCulture);
            }
        }
    }
}
