//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.Models.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba objektów na stronie musi być większa od 0..
        /// </summary>
        internal static string ItemsPerPageErrorMessage {
            get {
                return ResourceManager.GetString("ItemsPerPageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KRS ma format 0000000000.
        /// </summary>
        internal static string KrsDescription {
            get {
                return ResourceManager.GetString("KrsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KRS ma format 0000000000.
        /// </summary>
        internal static string KrsErrorMessage {
            get {
                return ResourceManager.GetString("KrsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP ma format 0000000000.
        /// </summary>
        internal static string NipDescription {
            get {
                return ResourceManager.GetString("NipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP ma format 0000000000.
        /// </summary>
        internal static string NipErrorMessage {
            get {
                return ResourceManager.GetString("NipErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer strony musi być większy od 0..
        /// </summary>
        internal static string PageErrorMessage {
            get {
                return ResourceManager.GetString("PageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON ma format 000000000 lub 00000000000000.
        /// </summary>
        internal static string RegonDescription {
            get {
                return ResourceManager.GetString("RegonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON ma format 000000000 lub 00000000000000 .
        /// </summary>
        internal static string RegonErrorMessage {
            get {
                return ResourceManager.GetString("RegonErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieznany typ.
        /// </summary>
        internal static string UnknownType {
            get {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }
    }
}
