//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RADON.Contracts.Descriptions.Institutions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QueryParameter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryParameter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RADON.Contracts.Descriptions.Institutions.QueryParameter", typeof(QueryParameter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejscowość filii / Branch city..
        /// </summary>
        public static string institution_branch_city_description {
            get {
                return ResourceManager.GetString("institution_branch_city_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejscowość instytucji / Institution city..
        /// </summary>
        public static string institution_city_description {
            get {
                return ResourceManager.GetString("institution_city_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer wpisu do ewidencji uczelni niepublicznych / Nonpublic university number..
        /// </summary>
        public static string institution_eun_number_description {
            get {
                return ResourceManager.GetString("institution_eun_number_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj instytucji - tablica kodów słownikowych. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Array of codes of institution kinds. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string institution_i_kind_cd_description {
            get {
                return ResourceManager.GetString("institution_i_kind_cd_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data utworzenia instytucji - od / Institution creation date from..
        /// </summary>
        public static string institution_i_start_date_from_description {
            get {
                return ResourceManager.GetString("institution_i_start_date_from_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data utworzenia instytucji - do / Institution creation date to..
        /// </summary>
        public static string institution_i_start_date_to_description {
            get {
                return ResourceManager.GetString("institution_i_start_date_to_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id instytucji / Id of institution..
        /// </summary>
        public static string institution_id_description {
            get {
                return ResourceManager.GetString("institution_id_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stary identyfikator instytucji - uid instytucji z POL-on 1.0 / Old institution identifier - POL-on 1.0 system uid..
        /// </summary>
        public static string institution_institution_uid_description {
            get {
                return ResourceManager.GetString("institution_institution_uid_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator instytucji - uuid instytucji z POL-on 2.0 / Institution identifier - POL-on 2.0 system uuid..
        /// </summary>
        public static string institution_institution_uuid_description {
            get {
                return ResourceManager.GetString("institution_institution_uuid_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer KRS / National Court Register number (KRS number)..
        /// </summary>
        public static string institution_krs_description {
            get {
                return ResourceManager.GetString("institution_krs_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja o czasie ostatniego odświeżania danych (znacznik czasu - bieżący czas uniksowy w milisekundach) / Information about the last data refresh time (timestamp - current Unix epoch time in milliseconds)..
        /// </summary>
        public static string institution_last_refresh_description {
            get {
                return ResourceManager.GetString("institution_last_refresh_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer uczelni nadany przez ministra / University number given by minister..
        /// </summary>
        public static string institution_ministry_number_description {
            get {
                return ResourceManager.GetString("institution_ministry_number_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa instytucji / Name of institution in given language..
        /// </summary>
        public static string institution_name_description {
            get {
                return ResourceManager.GetString("institution_name_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP / Tax Identification Number (NIP)..
        /// </summary>
        public static string institution_nip_description {
            get {
                return ResourceManager.GetString("institution_nip_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer rejestru instytutów PAN / Number in the register of PAS institutes (Polish Academy of Sciences)..
        /// </summary>
        public static string institution_pan_number_description {
            get {
                return ResourceManager.GetString("institution_pan_number_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Państwowy Instytut Badawczy (PIB) - znacznik instytucji posiadającej status PIB / National Research Institute (PIB) status marker..
        /// </summary>
        public static string institution_pib_description {
            get {
                return ResourceManager.GetString("institution_pib_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON instytucji / REGON of institution..
        /// </summary>
        public static string institution_regon_description {
            get {
                return ResourceManager.GetString("institution_regon_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametr określający liczbę wyników, która ma być zwrócona w odpowiedzi. Domyślna wartość = 10. Maksymalna wartość = 100. / Number of elements to return. Number of results that you want to receive. Default value = 10. Maximum value = 100..
        /// </summary>
        public static string institution_result_numbers_description {
            get {
                return ResourceManager.GetString("institution_result_numbers_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ instytucji naukowej - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Code of scientific institution type. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string institution_si_type_cd_description {
            get {
                return ResourceManager.GetString("institution_si_type_cd_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status instytucji - tablica kodów słownikowych. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Array of codes of institution statuses. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string institution_status_code_description {
            get {
                return ResourceManager.GetString("institution_status_code_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID instytucji nadzorującej. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Supervising institution id. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string institution_supervising_institution_id_description {
            get {
                return ResourceManager.GetString("institution_supervising_institution_id_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Każda poprawna odpowiedź usługi zawiera dane oraz token, który umożliwia pobranie kolejnej partii danych. Przy pierwszym wywołaniu usługi token musi być pustym stringiem. Pobieranie kolejnych stron z wynikami odbywa się z użyciem tokenu, który został zwrócony w poprzedniej odpowiedzi / At the first time the token must be empty string. The new token (after first search) is generated in response and must be forwarded to query if you want to get the next results..
        /// </summary>
        public static string institution_token_description {
            get {
                return ResourceManager.GetString("institution_token_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ uczelni - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Code of university type. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string institution_u_type_cd_description {
            get {
                return ResourceManager.GetString("institution_u_type_cd_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Województwo - kod. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Branch voivodeship code. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string institution_voivodeship_code_description {
            get {
                return ResourceManager.GetString("institution_voivodeship_code_description", resourceCulture);
            }
        }
    }
}
