//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RADON.Contracts.Descriptions.Institutions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Response {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Response() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RADON.Contracts.Descriptions.Institutions.Response", typeof(Response).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod słownikowy / Available code which is generated automatically..
        /// </summary>
        public static string dictionary_code {
            get {
                return ResourceManager.GetString("dictionary_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod słownikowy / Available code which is generated automatically..
        /// </summary>
        public static string dictionary_code1 {
            get {
                return ResourceManager.GetString("dictionary_code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa angielska / Text in English..
        /// </summary>
        public static string dictionary_name_en {
            get {
                return ResourceManager.GetString("dictionary_name_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa angielska / Text in English..
        /// </summary>
        public static string dictionary_name_en1 {
            get {
                return ResourceManager.GetString("dictionary_name_en1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa polska / Text in Polish..
        /// </summary>
        public static string dictionary_name_pl {
            get {
                return ResourceManager.GetString("dictionary_name_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa polska / Text in Polish..
        /// </summary>
        public static string dictionary_name_pl1 {
            get {
                return ResourceManager.GetString("dictionary_name_pl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model słownika / Model of Dictionary..
        /// </summary>
        public static string dictionary_value {
            get {
                return ResourceManager.GetString("dictionary_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model słownika / Model of Dictionary..
        /// </summary>
        public static string dictionary_value1 {
            get {
                return ResourceManager.GetString("dictionary_value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer budynku / Building number..
        /// </summary>
        public static string institution_address_b_number {
            get {
                return ResourceManager.GetString("institution_address_b_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto / City..
        /// </summary>
        public static string institution_address_city {
            get {
                return ResourceManager.GetString("institution_address_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj / Country..
        /// </summary>
        public static string institution_address_country {
            get {
                return ResourceManager.GetString("institution_address_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane adresu instytucji / Institution address data..
        /// </summary>
        public static string institution_address_data {
            get {
                return ResourceManager.GetString("institution_address_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data otrzymania adresu / Address from date..
        /// </summary>
        public static string institution_address_date_from {
            get {
                return ResourceManager.GetString("institution_address_date_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer mieszkania / House number..
        /// </summary>
        public static string institution_address_l_number {
            get {
                return ResourceManager.GetString("institution_address_l_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy / Postal code..
        /// </summary>
        public static string institution_address_postal_cd {
            get {
                return ResourceManager.GetString("institution_address_postal_cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica / Street..
        /// </summary>
        public static string institution_address_street {
            get {
                return ResourceManager.GetString("institution_address_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Województwo / Voivodeship..
        /// </summary>
        public static string institution_address_voivodeship {
            get {
                return ResourceManager.GetString("institution_address_voivodeship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia zmian adresu instytucji / History of institution address changes..
        /// </summary>
        public static string institution_addresses {
            get {
                return ResourceManager.GetString("institution_addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer budynku / Building number..
        /// </summary>
        public static string institution_b_number {
            get {
                return ResourceManager.GetString("institution_b_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer wpisu do ewidencji uczelni niepublicznych / Nonpublic university number..
        /// </summary>
        public static string institution_base_institution_eun_number {
            get {
                return ResourceManager.GetString("institution_base_institution_eun_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer KRS / National Court Register number (KRS number)..
        /// </summary>
        public static string institution_base_institution_krs {
            get {
                return ResourceManager.GetString("institution_base_institution_krs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP / Tax Identification Number (NIP)..
        /// </summary>
        public static string institution_base_institution_nip {
            get {
                return ResourceManager.GetString("institution_base_institution_nip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer rejestru instytutów PAN / Number in the register of PAS institutes (Polish Academy of Sciences)..
        /// </summary>
        public static string institution_base_institution_pan_number {
            get {
                return ResourceManager.GetString("institution_base_institution_pan_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON / Institution REGON..
        /// </summary>
        public static string institution_base_institution_regon {
            get {
                return ResourceManager.GetString("institution_base_institution_regon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID instytucji nadzorującej. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Supervising institution id. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string institution_base_institution_supervising_institution_id {
            get {
                return ResourceManager.GetString("institution_base_institution_supervising_institution_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa instytucji nadzorującej / Supervising institution name.
        /// </summary>
        public static string institution_base_institution_supervising_institution_name {
            get {
                return ResourceManager.GetString("institution_base_institution_supervising_institution_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data przekształcenia / Transformation date..
        /// </summary>
        public static string institution_base_institution_transformation_date {
            get {
                return ResourceManager.GetString("institution_base_institution_transformation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj przekształcenia / Type of transformation..
        /// </summary>
        public static string institution_base_institution_transformation_kind {
            get {
                return ResourceManager.GetString("institution_base_institution_transformation_kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejscowość filii / Branch city..
        /// </summary>
        public static string institution_branch_branch_city {
            get {
                return ResourceManager.GetString("institution_branch_branch_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa filii / Branch name..
        /// </summary>
        public static string institution_branch_branch_name {
            get {
                return ResourceManager.GetString("institution_branch_branch_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator filii - uuid z POL-on 2.0 / Branch identifier - POL-on 2.0 system uuid..
        /// </summary>
        public static string institution_branch_branch_uuid {
            get {
                return ResourceManager.GetString("institution_branch_branch_uuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane filii podlegającej pod instytucję / Institution branch data..
        /// </summary>
        public static string institution_branch_data {
            get {
                return ResourceManager.GetString("institution_branch_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto / City..
        /// </summary>
        public static string institution_city {
            get {
                return ResourceManager.GetString("institution_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj / Country..
        /// </summary>
        public static string institution_country {
            get {
                return ResourceManager.GetString("institution_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj - kod / Code of country..
        /// </summary>
        public static string institution_country_cd {
            get {
                return ResourceManager.GetString("institution_country_cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja o źródle danych / Information about data source..
        /// </summary>
        public static string institution_data_source {
            get {
                return ResourceManager.GetString("institution_data_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres e-mail / E-mail address..
        /// </summary>
        public static string institution_e_mail {
            get {
                return ResourceManager.GetString("institution_e_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres do doręczeń elektronicznych (EDA)/ EDA - Electronic delivery address..
        /// </summary>
        public static string institution_eda_address {
            get {
                return ResourceManager.GetString("institution_eda_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres elektronicznej skrzynki podawczej (ESP) / ESP - electronic inbox address..
        /// </summary>
        public static string institution_esp_address {
            get {
                return ResourceManager.GetString("institution_esp_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer wpisu do ewidencji uczelni niepublicznych / Nonpublic university number..
        /// </summary>
        public static string institution_eun_number {
            get {
                return ResourceManager.GetString("institution_eun_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane instytucji wchodzacych w skład federacji / Data of the federation institutions..
        /// </summary>
        public static string institution_federation_institution_data {
            get {
                return ResourceManager.GetString("institution_federation_institution_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W federacji od / Date from..
        /// </summary>
        public static string institution_federation_institution_date_from {
            get {
                return ResourceManager.GetString("institution_federation_institution_date_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W federacji do / Date to..
        /// </summary>
        public static string institution_federation_institution_date_to {
            get {
                return ResourceManager.GetString("institution_federation_institution_date_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa instytucji / Institution name..
        /// </summary>
        public static string institution_federation_institution_institution_name {
            get {
                return ResourceManager.GetString("institution_federation_institution_institution_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator instytucji - uuid z POL-on 2.0 / Institution identifier - POL-on 2.0 system uuid..
        /// </summary>
        public static string institution_federation_institution_institution_uuid {
            get {
                return ResourceManager.GetString("institution_federation_institution_institution_uuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer w rejestrze federacji / Federation registry number..
        /// </summary>
        public static string institution_federation_number {
            get {
                return ResourceManager.GetString("institution_federation_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj instytucji - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Code of institution kind. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string institution_i_kind_cd {
            get {
                return ResourceManager.GetString("institution_i_kind_cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj instytucji - nazwa / Name of institution kind..
        /// </summary>
        public static string institution_i_kind_name {
            get {
                return ResourceManager.GetString("institution_i_kind_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data likwidacji (jeśli dotyczy) / Institution liquidation date..
        /// </summary>
        public static string institution_i_liq_dt {
            get {
                return ResourceManager.GetString("institution_i_liq_dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data postawienia w stan likwidacji (jeśli dotyczy) / Institution liquidation start date..
        /// </summary>
        public static string institution_i_liq_start_dt {
            get {
                return ResourceManager.GetString("institution_i_liq_start_dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data utworzenia instytucji / Institution creation date..
        /// </summary>
        public static string institution_i_start_dt {
            get {
                return ResourceManager.GetString("institution_i_start_dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID instytucji / Id of institution..
        /// </summary>
        public static string institution_id {
            get {
                return ResourceManager.GetString("institution_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stary identyfikator instytucji - uid instytucji z POL-on 1.0 / Old institution identifier - POL-on 1.0 system uid..
        /// </summary>
        public static string institution_institution_uid {
            get {
                return ResourceManager.GetString("institution_institution_uid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator instytucji - uuid instytucji z POL-on 2.0 / Institution identifier - POL-on 2.0 system uuid..
        /// </summary>
        public static string institution_institution_uuid {
            get {
                return ResourceManager.GetString("institution_institution_uuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer KRS / National Court Register number (KRS number)..
        /// </summary>
        public static string institution_krs {
            get {
                return ResourceManager.GetString("institution_krs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer mieszkania / House number.
        /// </summary>
        public static string institution_l_number {
            get {
                return ResourceManager.GetString("institution_l_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje o czasie ostatniego odświeżania danych (znacznik czasu - bieżący czas uniksowy w milisekundach) / Information about the last data refresh time (timestamp - current Unix epoch time in milliseconds)..
        /// </summary>
        public static string institution_last_refresh {
            get {
                return ResourceManager.GetString("institution_last_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator zatrudnienia pracownika (osoby kierującej podmiotem) w instytucji / Manager employee in institution identifier..
        /// </summary>
        public static string institution_manager_employee_in_institution_uuid {
            get {
                return ResourceManager.GetString("institution_manager_employee_in_institution_uuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stanowisko/funkcja osoby kierującej podmiotem / Manager function name..
        /// </summary>
        public static string institution_manager_function {
            get {
                return ResourceManager.GetString("institution_manager_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię osoby kierującej podmiotem / Manager name..
        /// </summary>
        public static string institution_manager_name {
            get {
                return ResourceManager.GetString("institution_manager_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozostałe imiona osoby kierującej podmiotem / Manager other names..
        /// </summary>
        public static string institution_manager_other_names {
            get {
                return ResourceManager.GetString("institution_manager_other_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko osoby kierującej podmiotem / Manager surnname..
        /// </summary>
        public static string institution_manager_surname {
            get {
                return ResourceManager.GetString("institution_manager_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przedrostek nazwiska osoby kierującej podmiotem / Manager surnname prefix..
        /// </summary>
        public static string institution_manager_surname_prefix {
            get {
                return ResourceManager.GetString("institution_manager_surname_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer uczelni nadany przez ministra / University number given by minister..
        /// </summary>
        public static string institution_ministry_number {
            get {
                return ResourceManager.GetString("institution_ministry_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa instytucji / Institution name..
        /// </summary>
        public static string institution_name {
            get {
                return ResourceManager.GetString("institution_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane nazwy instytucji / Institution name data..
        /// </summary>
        public static string institution_name_data {
            get {
                return ResourceManager.GetString("institution_name_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data nadania nazwy / Date from..
        /// </summary>
        public static string institution_name_data_date_from {
            get {
                return ResourceManager.GetString("institution_name_data_date_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa instytucji / Institution name..
        /// </summary>
        public static string institution_name_data_name {
            get {
                return ResourceManager.GetString("institution_name_data_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia zmian nazw instytucji / History of institution name changes..
        /// </summary>
        public static string institution_names {
            get {
                return ResourceManager.GetString("institution_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP / Tax Identification Number (NIP)..
        /// </summary>
        public static string institution_nip {
            get {
                return ResourceManager.GetString("institution_nip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer rejestru instytutów PAN / Number in the register of PAS institutes (Polish Academy of Sciences)..
        /// </summary>
        public static string institution_pan_number {
            get {
                return ResourceManager.GetString("institution_pan_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer telefonu / Phone number.
        /// </summary>
        public static string institution_phone {
            get {
                return ResourceManager.GetString("institution_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Państwowy Instytut Badawczy (PIB) - znacznik instytucji posiadającej status PIB / National Research Institute (PIB) status marker..
        /// </summary>
        public static string institution_pib {
            get {
                return ResourceManager.GetString("institution_pib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy / Postal code..
        /// </summary>
        public static string institution_postal_cd {
            get {
                return ResourceManager.GetString("institution_postal_cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGON / Institution REGON..
        /// </summary>
        public static string institution_regon {
            get {
                return ResourceManager.GetString("institution_regon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ instytucji naukowej - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Code of scientific institution type. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string institution_si_type_cd {
            get {
                return ResourceManager.GetString("institution_si_type_cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ instytucji naukowej - nazwa / Name of scientific institution type..
        /// </summary>
        public static string institution_si_type_name {
            get {
                return ResourceManager.GetString("institution_si_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status instytucji / Institution status.
        /// </summary>
        public static string institution_status {
            get {
                return ResourceManager.GetString("institution_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status instytucji - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Code of institution status. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string institution_status_code {
            get {
                return ResourceManager.GetString("institution_status_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane statusu instytucji / Institution status data..
        /// </summary>
        public static string institution_status_data {
            get {
                return ResourceManager.GetString("institution_status_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data nadania statusu / Date of granting the status..
        /// </summary>
        public static string institution_status_date_from {
            get {
                return ResourceManager.GetString("institution_status_date_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa statusu / Status name.
        /// </summary>
        public static string institution_status_name {
            get {
                return ResourceManager.GetString("institution_status_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia zmian statusu instytucji / History of institution status changes..
        /// </summary>
        public static string institution_statuses {
            get {
                return ResourceManager.GetString("institution_statuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica / Street..
        /// </summary>
        public static string institution_street {
            get {
                return ResourceManager.GetString("institution_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane organu nadzorującego / Supervising institution data..
        /// </summary>
        public static string institution_supervising_institution_data {
            get {
                return ResourceManager.GetString("institution_supervising_institution_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data przypisania do organu / Date of assignment to authority..
        /// </summary>
        public static string institution_supervising_institution_date_from {
            get {
                return ResourceManager.GetString("institution_supervising_institution_date_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID instytucji nadzorującej. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Supervising institution id. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string institution_supervising_institution_id {
            get {
                return ResourceManager.GetString("institution_supervising_institution_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa instytucji nadzorującej / Supervising institution name..
        /// </summary>
        public static string institution_supervising_institution_name {
            get {
                return ResourceManager.GetString("institution_supervising_institution_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia zmian organu nadzorującego instytucję / History of institution supervisory authority changes..
        /// </summary>
        public static string institution_supervising_institutions {
            get {
                return ResourceManager.GetString("institution_supervising_institutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane instytucji, na które bieżąca instytucja została przekształcona (instytucje dziedziczące) / Institutions into which the current institution has been transformed (inheriting institutions).
        /// </summary>
        public static string institution_target_institution_data {
            get {
                return ResourceManager.GetString("institution_target_institution_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa instytucji / Target institution name..
        /// </summary>
        public static string institution_target_institution_target_institution_name {
            get {
                return ResourceManager.GetString("institution_target_institution_target_institution_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator instytucji - uuid z POL-on 2.0 / Target institution identifier - POL-on 2.0 system uuid..
        /// </summary>
        public static string institution_target_institution_target_institution_uuid {
            get {
                return ResourceManager.GetString("institution_target_institution_target_institution_uuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane instytucji przekształconych na bieżącą instytucję (instytucje poprzedzające) / Institutions transformed into the current institution (predecessor institutions)..
        /// </summary>
        public static string institution_transformed_institution_data {
            get {
                return ResourceManager.GetString("institution_transformed_institution_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa przekształconej instytucji / Transformed institution name..
        /// </summary>
        public static string institution_transformed_institution_transformed_institution_name {
            get {
                return ResourceManager.GetString("institution_transformed_institution_transformed_institution_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator przekształconej instytucji - uuid z POL-on 2.0 / Transformed institution identifier - POL-on 2.0 system uuid..
        /// </summary>
        public static string institution_transformed_institution_transformed_institution_uuid {
            get {
                return ResourceManager.GetString("institution_transformed_institution_transformed_institution_uuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane typu instytucji / Institution type data.
        /// </summary>
        public static string institution_type_data {
            get {
                return ResourceManager.GetString("institution_type_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data nadania typu / Date of type assignment..
        /// </summary>
        public static string institution_type_date_from {
            get {
                return ResourceManager.GetString("institution_type_date_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa typu / Type name..
        /// </summary>
        public static string institution_type_name {
            get {
                return ResourceManager.GetString("institution_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia zmian typu instytucji / History of institution type changes..
        /// </summary>
        public static string institution_types {
            get {
                return ResourceManager.GetString("institution_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ uczelni - kod słownikowy. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Code of university type. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string institution_u_type_cd {
            get {
                return ResourceManager.GetString("institution_u_type_cd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ uczelni - nazwa / Name of university type..
        /// </summary>
        public static string institution_u_type_name {
            get {
                return ResourceManager.GetString("institution_u_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Województwo / Voivodeship..
        /// </summary>
        public static string institution_voivodeship {
            get {
                return ResourceManager.GetString("institution_voivodeship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Województwo - kod. Skorzystaj z usług słownikowych, aby uzyskać więcej informacji / Branch voivodeship code. Use Dictionary&apos;s services to receive extended information..
        /// </summary>
        public static string institution_voivodeship_code {
            get {
                return ResourceManager.GetString("institution_voivodeship_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres strony WWW / Web address..
        /// </summary>
        public static string institution_www {
            get {
                return ResourceManager.GetString("institution_www", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok uzyskania statusu Państwowego Instytutu Badawczego / Year of obtaining National Research Institute (PIB) status..
        /// </summary>
        public static string institution_year_pib {
            get {
                return ResourceManager.GetString("institution_year_pib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalna liczba wyników dla danego zapytania / The maximum number of results to be taken for a given query..
        /// </summary>
        public static string max_count {
            get {
                return ResourceManager.GetString("max_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Każda poprawna odpowiedź usługi zawiera dane oraz token, który umożliwia pobranie kolejnej partii danych. Pobieranie kolejnej strony z wynikami odbywa się z użyciem tokenu, który został zwrócony w poprzedniej odpowiedzi (parametr &apos;token&apos; w zapytaniu) / The token is generated after first search. It must be forwarded to QueryParameters (token field) to take next page of results..
        /// </summary>
        public static string token {
            get {
                return ResourceManager.GetString("token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
