//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RADON.Models.Descriptions.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Response {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Response() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RADON.Models.Descriptions.Shared.Response", typeof(Response).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista obiektów wynikowych. Jeśli nie znaleziono rekordów, zwracana jest pusta lista. / A list of result objects. If no records are found, an empty list is returned..
        /// </summary>
        public static string Response_Items {
            get {
                return ResourceManager.GetString("Response_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obiekt zawierający szczegóły dotyczące stronicowania. / An object containing pagination details..
        /// </summary>
        public static string Response_Pagination {
            get {
                return ResourceManager.GetString("Response_Pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa przechowująca informacje o stanie stronicowania danych. / Class storing information about the data pagination state..
        /// </summary>
        public static string ResponsePagination {
            get {
                return ResourceManager.GetString("ResponsePagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba elementów przypadająca na jedną stronę (rozmiar strony). / Number of items per page (page size)..
        /// </summary>
        public static string ResponsePagination_ItemsPerPage {
            get {
                return ResourceManager.GetString("ResponsePagination_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer bieżącej strony (indeksowany zazwyczaj od 1). / The current page number (usually indexed from 1)..
        /// </summary>
        public static string ResponsePagination_Page {
            get {
                return ResourceManager.GetString("ResponsePagination_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Całkowita liczba wszystkich elementów w bazie danych spełniających kryteria wyszukiwania. / Total number of all items in the database that meet the search criteria..
        /// </summary>
        public static string ResponsePagination_TotalCount {
            get {
                return ResourceManager.GetString("ResponsePagination_TotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniwersalny kontener dla odpowiedzi API zwracających listy obiektów. / A universal container for API responses returning lists of objects..
        /// </summary>
        public static string ResponseT {
            get {
                return ResourceManager.GetString("ResponseT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja o bieżącym czasie systemowym serwera. Używana do synchronizacji czasu między klientem a serwerem. / Information about the current system time of the server. Used for time synchronization between the client and the server..
        /// </summary>
        public static string ServerTimeResponse {
            get {
                return ResourceManager.GetString("ServerTimeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bieżąca data i godzina serwera wraz z przesunięciem czasowym (ISO 8601). / Current server date and time with time zone offset (ISO 8601)..
        /// </summary>
        public static string ServerTimeResponse_CurrentDateTime {
            get {
                return ResourceManager.GetString("ServerTimeResponse_CurrentDateTime", resourceCulture);
            }
        }
    }
}
