//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RADON.Models.Descriptions.Courses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QueryParameter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryParameter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RADON.Models.Descriptions.Courses.QueryParameter", typeof(QueryParameter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa definiuje kryteria filtrowania, parametryzacji oraz identyfikacji kierunków studiów w zapytaniach typu GET. Stanowi pomost pomiędzy parametrami przekazanymi w adresie URL a logiką przeszukiwania bazy danych Twojej aplikacji, przechowującej dane o edukacji. / The class defines filtering, parameterization, and identification criteria for study courses in GET requests. It acts as a bridge between URL query parameters and the search logic of your application&apos;s database, which stores educational data..
        /// </summary>
        public static string QueryParameters {
            get {
                return ResourceManager.GetString("QueryParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista identyfikatorów konkretnych uruchomień kierunku. / Collection of course instance UUIDs..
        /// </summary>
        public static string QueryParameters_CourseInstanceUuids {
            get {
                return ResourceManager.GetString("QueryParameters_CourseInstanceUuids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista identyfikatorów UUID kierunków studiów. / Collection of course UUIDs..
        /// </summary>
        public static string QueryParameters_CourseUuids {
            get {
                return ResourceManager.GetString("QueryParameters_CourseUuids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kody dyscyplin naukowych przypisanych do kierunku. / Discipline codes..
        /// </summary>
        public static string QueryParameters_DisciplineCodes {
            get {
                return ResourceManager.GetString("QueryParameters_DisciplineCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kody form kształcenia (np. stacjonarne). / Course form codes..
        /// </summary>
        public static string QueryParameters_FormCodes {
            get {
                return ResourceManager.GetString("QueryParameters_FormCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kody statusów konkretnych uruchomień. / Course instance status codes..
        /// </summary>
        public static string QueryParameters_InstanceStatusCodes {
            get {
                return ResourceManager.GetString("QueryParameters_InstanceStatusCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista identyfikatorów UUID instytucji prowadzących. / Collection of institution UUIDs..
        /// </summary>
        public static string QueryParameters_InstitutionUuids {
            get {
                return ResourceManager.GetString("QueryParameters_InstitutionUuids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy są to studia pomostowe? / Bridging course marker..
        /// </summary>
        public static string QueryParameters_IsBridging {
            get {
                return ResourceManager.GetString("QueryParameters_IsBridging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kody klasyfikacji ISCED. / ISCED classification codes..
        /// </summary>
        public static string QueryParameters_IscedCodes {
            get {
                return ResourceManager.GetString("QueryParameters_IscedCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy studia prowadzone są we współpracy z organizacją zawodową? / Cooperation with vocational marker..
        /// </summary>
        public static string QueryParameters_IsCoopWithVocational {
            get {
                return ResourceManager.GetString("QueryParameters_IsCoopWithVocational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy studia mają charakter dualny? / Dual course marker..
        /// </summary>
        public static string QueryParameters_IsDual {
            get {
                return ResourceManager.GetString("QueryParameters_IsDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy studia są filologiczne? / Philological studies marker..
        /// </summary>
        public static string QueryParameters_IsPhilological {
            get {
                return ResourceManager.GetString("QueryParameters_IsPhilological", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy studia przygotowują do zawodu nauczyciela? / Teacher training marker..
        /// </summary>
        public static string QueryParameters_IsTeacherTraining {
            get {
                return ResourceManager.GetString("QueryParameters_IsTeacherTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kody języków wykładowych. / Education language codes..
        /// </summary>
        public static string QueryParameters_LanguageCodes {
            get {
                return ResourceManager.GetString("QueryParameters_LanguageCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kody poziomów kształcenia (np. studia pierwszego stopnia). / Course level codes..
        /// </summary>
        public static string QueryParameters_LevelCodes {
            get {
                return ResourceManager.GetString("QueryParameters_LevelCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr tekstowy dla nazwy kierunku. / Search filter for course name..
        /// </summary>
        public static string QueryParameters_Name {
            get {
                return ResourceManager.GetString("QueryParameters_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kody języków filologii obcej. / Philology language codes..
        /// </summary>
        public static string QueryParameters_PhilologicalLanguageCodes {
            get {
                return ResourceManager.GetString("QueryParameters_PhilologicalLanguageCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kody tytułów zawodowych nadawanych absolwentom. / Professional title codes..
        /// </summary>
        public static string QueryParameters_ProfessionalTitleCodes {
            get {
                return ResourceManager.GetString("QueryParameters_ProfessionalTitleCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kody profilów kształcenia (np. ogólnoakademicki). / Course profile codes..
        /// </summary>
        public static string QueryParameters_ProfileCodes {
            get {
                return ResourceManager.GetString("QueryParameters_ProfileCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kody statusów kierunku. / Course status codes..
        /// </summary>
        public static string QueryParameters_StatusCodes {
            get {
                return ResourceManager.GetString("QueryParameters_StatusCodes", resourceCulture);
            }
        }
    }
}
