//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RADON.Models.Descriptions.Courses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Response {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Response() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RADON.Models.Descriptions.Courses.Response", typeof(Response).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa ta reprezentuje szczegółowe dane o kierunku studiów, obejmujące identyfikatory, ramy czasowe prowadzenia kształcenia, klasyfikacje (poziom, profil, ISCED) oraz przypisane dyscypliny naukowe i konkretne uruchomienia. / The class represents detailed information about a field of study, including identifiers, education timeframes, classifications (level, profile, ISCED), assigned scientific disciplines, and specific course instances..
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolekcja konkretnych uruchomień (edycji) danego kierunku. / Collection of specific instances (editions) of the course..
        /// </summary>
        public static string Course_CourseInstances {
            get {
                return ResourceManager.GetString("Course_CourseInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator kierunku - uuid z systemu POL-on 2.0. / Course identifier - POL-on 2 system uuid..
        /// </summary>
        public static string Course_CourseUuid {
            get {
                return ResourceManager.GetString("Course_CourseUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data rozpoczęcia prowadzenia studiów na kierunku. / Education start date..
        /// </summary>
        public static string Course_CreationDate {
            get {
                return ResourceManager.GetString("Course_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja o źródle pochodzenia danych. / Information about data source..
        /// </summary>
        public static string Course_DataSource {
            get {
                return ResourceManager.GetString("Course_DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista dyscyplin przypisanych do kierunku wraz z ich udziałem. / List of disciplines assigned to the course with their shares..
        /// </summary>
        public static string Course_Disciplines {
            get {
                return ResourceManager.GetString("Course_Disciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator instytucji prowadzącej studia. / Leading institution identifier - uuid..
        /// </summary>
        public static string Course_InstitutionUuid {
            get {
                return ResourceManager.GetString("Course_InstitutionUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasyfikacja ISCED dla kierunku. / ISCED classification..
        /// </summary>
        public static string Course_Isced {
            get {
                return ResourceManager.GetString("Course_Isced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy studia dotyczą filologii obcej? / Philological course marker..
        /// </summary>
        public static string Course_IsPhilological {
            get {
                return ResourceManager.GetString("Course_IsPhilological", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy studia przygotowują do zawodu nauczyciela? / Teacher training marker..
        /// </summary>
        public static string Course_IsTeacherTraining {
            get {
                return ResourceManager.GetString("Course_IsTeacherTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas ostatniego odświeżania danych w lokalnej bazie. / Last refresh time in the local database..
        /// </summary>
        public static string Course_LastRefresh {
            get {
                return ResourceManager.GetString("Course_LastRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poziom kształcenia (np. studia pierwszego stopnia). / Course level..
        /// </summary>
        public static string Course_Level {
            get {
                return ResourceManager.GetString("Course_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data likwidacji kierunku (jeśli dotyczy). / Course liquidation date..
        /// </summary>
        public static string Course_LiquidationDate {
            get {
                return ResourceManager.GetString("Course_LiquidationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa kierunku studiów. / Course name..
        /// </summary>
        public static string Course_Name {
            get {
                return ResourceManager.GetString("Course_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil kształcenia (np. ogólnoakademicki). / Course profile..
        /// </summary>
        public static string Course_Profile {
            get {
                return ResourceManager.GetString("Course_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas ostatniego odświeżania danych w systemie źródłowym. / Last refresh time in the source system..
        /// </summary>
        public static string Course_SourceLastRefresh {
            get {
                return ResourceManager.GetString("Course_SourceLastRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualny status kierunku studiów. / Current course status..
        /// </summary>
        public static string Course_Status {
            get {
                return ResourceManager.GetString("Course_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data początku wygaszania kierunku (jeśli dotyczy). / Course termination initialization date..
        /// </summary>
        public static string Course_TerminationInitializationDate {
            get {
                return ResourceManager.GetString("Course_TerminationInitializationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klasa przechowuje szczegółowe informacje o konkretnym uruchomieniu kierunku studiów. Zawiera dane o formie kształcenia, czasie trwania, języku oraz uzyskanych tytułach zawodowych, odzwierciedlając strukturę danych przechowywaną w lokalnej bazie na podstawie systemu POL-on. / The class stores detailed information about a specific course instance. It includes data on the form of education, duration, language, and professional titles, reflecting the data structure stored in the local database based on the POL- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CourseInstance {
            get {
                return ResourceManager.GetString("CourseInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator uruchomienia - uuid z POL-on 2.0. / Course instance identifier - POL-on 2 system uuid..
        /// </summary>
        public static string CourseInstance_CourseInstanceUuid {
            get {
                return ResourceManager.GetString("CourseInstance_CourseInstanceUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba punktów ECTS wymagana do uzyskania kwalifikacji. / ECTS points required for qualification..
        /// </summary>
        public static string CourseInstance_Ects {
            get {
                return ResourceManager.GetString("CourseInstance_Ects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data rozpoczęcia kształcenia (uruchomienia). / Beginning of education date..
        /// </summary>
        public static string CourseInstance_EducationStartDate {
            get {
                return ResourceManager.GetString("CourseInstance_EducationStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma kształcenia (np. stacjonarne) – element słownikowy. / Course form (e.g., full-time) – dictionary item..
        /// </summary>
        public static string CourseInstance_Form {
            get {
                return ResourceManager.GetString("CourseInstance_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znacznik, czy są to studia pomostowe. / Bridging course marker..
        /// </summary>
        public static string CourseInstance_IsBridging {
            get {
                return ResourceManager.GetString("CourseInstance_IsBridging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy studia prowadzone we współpracy z organizacją zawodową? / Cooperation with vocational marker..
        /// </summary>
        public static string CourseInstance_IsCoopWithVocational {
            get {
                return ResourceManager.GetString("CourseInstance_IsCoopWithVocational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znacznik, czy są to studia dualne. / Dual course marker..
        /// </summary>
        public static string CourseInstance_IsDual {
            get {
                return ResourceManager.GetString("CourseInstance_IsDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Główny język kształcenia – element słownikowy. / Main language of education – dictionary item..
        /// </summary>
        public static string CourseInstance_Language {
            get {
                return ResourceManager.GetString("CourseInstance_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data likwidacji uruchomienia (jeśli dotyczy). / Course instance liquidation date..
        /// </summary>
        public static string CourseInstance_LiquidationDate {
            get {
                return ResourceManager.GetString("CourseInstance_LiquidationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa kierunku w ramach tego uruchomienia. / Course name within this instance..
        /// </summary>
        public static string CourseInstance_Name {
            get {
                return ResourceManager.GetString("CourseInstance_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba semestrów przewidziana w programie. / Number of semesters..
        /// </summary>
        public static string CourseInstance_NumberOfSemesters {
            get {
                return ResourceManager.GetString("CourseInstance_NumberOfSemesters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolekcja języków w przypadku filologii obcych. / Collection of philological languages..
        /// </summary>
        public static string CourseInstance_PhilologicalLanguages {
            get {
                return ResourceManager.GetString("CourseInstance_PhilologicalLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł zawodowy nadawany absolwentom – element słownikowy. / Professional title granted to graduates – dictionary item..
        /// </summary>
        public static string CourseInstance_ProfessionalTitle {
            get {
                return ResourceManager.GetString("CourseInstance_ProfessionalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status uruchomienia (np. aktywne) – element słownikowy. / Course instance status – dictionary item..
        /// </summary>
        public static string CourseInstance_Status {
            get {
                return ResourceManager.GetString("CourseInstance_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane o dyscyplinie naukowej kierunku / Course discipline data..
        /// </summary>
        public static string DisciplineData {
            get {
                return ResourceManager.GetString("DisciplineData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dyscyplina naukowa, w której uzyskiwane są efekty uczenia się. / Scientific discipline in which learning outcomes are achieved..
        /// </summary>
        public static string DisciplineData_Discipline {
            get {
                return ResourceManager.GetString("DisciplineData_Discipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znacznik określający, czy dana dyscyplina jest dyscypliną wiodącą. / Marker indicating whether the discipline is the leading one..
        /// </summary>
        public static string DisciplineData_IsLeading {
            get {
                return ResourceManager.GetString("DisciplineData_IsLeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udział procentowy dyscypliny w programie studiów. / Discipline percentage share in the study program..
        /// </summary>
        public static string DisciplineData_Percentage {
            get {
                return ResourceManager.GetString("DisciplineData_Percentage", resourceCulture);
            }
        }
    }
}
