<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b42135b5-cf09-43e8-b0ba-2a505eeceac0</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

	<ItemGroup Label="Docker">
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
	</ItemGroup>

	<ItemGroup Label="Scalar">
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Scalar.AspNetCore" />
	</ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Yarp.ReverseProxy" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\..\Base\Base.Models\Base.Models.csproj" />
  </ItemGroup>

</Project>
