<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Diploma.Application\Diploma.Application.csproj" />
    <ProjectReference Include="..\Diploma.Database.MsSql\Diploma.Database.MsSql.csproj" />
  </ItemGroup>

</Project>
