<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.10" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Backend\Base\Base.Models\Base.Models.csproj" />
    <ProjectReference Include="..\..\Backend\Diploma\Diploma.Models\Diploma.Models.csproj" />
    <ProjectReference Include="..\..\Backend\GUS.REGON\GUS.REGON.Models\GUS.REGON.Models.csproj" />
    <ProjectReference Include="..\..\Backend\RADON\RADON.Models\RADON.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\ProjectRecruitments\Layout\" />
  </ItemGroup>

</Project>
