//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RADON.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RADON.API.ApiDescription", typeof(ApiDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobiera dostępne formy studiów (stacjonarne, niestacjonarne). / Retrieves available course forms (full-time, part-time)..
        /// </summary>
        public static string GetCourseForms_Description {
            get {
                return ResourceManager.GetString("GetCourseForms_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownik form kształcenia / Course forms dictionary.
        /// </summary>
        public static string GetCourseForms_Summary {
            get {
                return ResourceManager.GetString("GetCourseForms_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobiera listę dostępnych poziomów kształcenia (np. studia pierwszego stopnia, jednolite magisterskie). / Retrieves a list of available education levels (e.g., first-cycle, long-cycle)..
        /// </summary>
        public static string GetCourseLevels_Description {
            get {
                return ResourceManager.GetString("GetCourseLevels_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownik poziomów kształcenia / Course levels dictionary.
        /// </summary>
        public static string GetCourseLevels_Summary {
            get {
                return ResourceManager.GetString("GetCourseLevels_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobiera listę dostępnych profilów kształcenia (ogólnoakademicki, praktyczny). / Retrieves a list of available course profiles (general academic, practical)..
        /// </summary>
        public static string GetCourseProfiles_Description {
            get {
                return ResourceManager.GetString("GetCourseProfiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownik profilów kształcenia / Course profiles dictionary.
        /// </summary>
        public static string GetCourseProfiles_Summary {
            get {
                return ResourceManager.GetString("GetCourseProfiles_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwraca listę kierunków studiów wraz z ich uruchomieniami, przefiltrowaną według zadanych kryteriów. / Returns a list of courses with their instances, filtered by given criteria..
        /// </summary>
        public static string GetCourses_Description {
            get {
                return ResourceManager.GetString("GetCourses_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobieranie listy kierunków studiów / Get list of courses.
        /// </summary>
        public static string GetCourses_Summary {
            get {
                return ResourceManager.GetString("GetCourses_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobiera listę statusów prawnych kierunków studiów. / Retrieves the list of legal statuses for courses..
        /// </summary>
        public static string GetCourseStatuses_Description {
            get {
                return ResourceManager.GetString("GetCourseStatuses_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownik statusów kierunków / Course statuses dictionary.
        /// </summary>
        public static string GetCourseStatuses_Summary {
            get {
                return ResourceManager.GetString("GetCourseStatuses_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwraca bieżący czas systemowy serwera w formacie ISO 8601, uwzględniając strefę czasową. Może być wykorzystany do synchronizacji operacji czasowych między klientem a systemem. / Returns the current system time of the server in ISO 8601 format, including the time zone offset. It can be used to synchronize time-sensitive operations between the client and the system..
        /// </summary>
        public static string GetCurrentTime_Description {
            get {
                return ResourceManager.GetString("GetCurrentTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobiera aktualną datę i godzinę serwera. / Retrieves the current server date and time..
        /// </summary>
        public static string GetCurrentTime_Summary {
            get {
                return ResourceManager.GetString("GetCurrentTime_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobiera pełną listę dyscyplin naukowych oraz artystycznych zgodnie z obowiązującą klasyfikacją. Słownik ten jest wspólny dla wielu modułów systemu (np. kierunków studiów i osiągnięć naukowych). / Retrieves a complete list of scientific and artistic disciplines according to the current classification. This dictionary is shared across multiple system modules..
        /// </summary>
        public static string GetDisciplines_Description {
            get {
                return ResourceManager.GetString("GetDisciplines_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownik dyscyplin naukowych i artystycznych. / Dictionary of scientific and artistic disciplines..
        /// </summary>
        public static string GetDisciplines_Summary {
            get {
                return ResourceManager.GetString("GetDisciplines_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobiera listę statusów dla konkretnych edycji (uruchomień) studiów. / Retrieves the list of statuses for specific course instances..
        /// </summary>
        public static string GetInstanceStatuses_Description {
            get {
                return ResourceManager.GetString("GetInstanceStatuses_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownik statusów uruchomień / Course instance statuses dictionary.
        /// </summary>
        public static string GetInstanceStatuses_Summary {
            get {
                return ResourceManager.GetString("GetInstanceStatuses_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobiera listę ogólnych rodzajów instytucji (np. uczelnia, instytut PAN, instytut badawczy). / Retrieves the list of general institution kinds (e.g., university, PAS institute, research institute)..
        /// </summary>
        public static string GetInstitutionKinds_Description {
            get {
                return ResourceManager.GetString("GetInstitutionKinds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownik rodzajów instytucji / Institution kinds dictionary.
        /// </summary>
        public static string GetInstitutionKinds_Summary {
            get {
                return ResourceManager.GetString("GetInstitutionKinds_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwraca szczegółową listę instytucji (uczelni, instytutów) wraz z historią zmian nazw i statusów, przefiltrowaną według parametrów. / Returns a detailed list of institutions (universities, institutes) with historical snapshots, filtered by parameters..
        /// </summary>
        public static string GetInstitutions_Description {
            get {
                return ResourceManager.GetString("GetInstitutions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobieranie listy instytucji / Get list of institutions.
        /// </summary>
        public static string GetInstitutions_Summary {
            get {
                return ResourceManager.GetString("GetInstitutions_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobiera listę statusów określających stan prawny instytucji (np. aktywna, zlikwidowana). / Retrieves the list of statuses defining the legal state of the institution..
        /// </summary>
        public static string GetInstitutionStatuses_Description {
            get {
                return ResourceManager.GetString("GetInstitutionStatuses_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownik statusów instytucji / Institution statuses dictionary.
        /// </summary>
        public static string GetInstitutionStatuses_Summary {
            get {
                return ResourceManager.GetString("GetInstitutionStatuses_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobiera kody i nazwy klasyfikacji ISCED-F (międzynarodowa klasyfikacja kierunków kształcenia). / Retrieves ISCED-F classification codes and names..
        /// </summary>
        public static string GetIsceds_Description {
            get {
                return ResourceManager.GetString("GetIsceds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownik klasyfikacji ISCED / ISCED classification dictionary.
        /// </summary>
        public static string GetIsceds_Summary {
            get {
                return ResourceManager.GetString("GetIsceds_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobiera listę języków, w których prowadzone jest kształcenie. / Retrieves the list of languages in which education is conducted..
        /// </summary>
        public static string GetLanguages_Description {
            get {
                return ResourceManager.GetString("GetLanguages_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownik języków wykładowych / Education languages dictionary.
        /// </summary>
        public static string GetLanguages_Summary {
            get {
                return ResourceManager.GetString("GetLanguages_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobiera listę tytułów zawodowych nadawanych absolwentom (licencjat, magister, inżynier). / Retrieves the list of professional titles awarded to graduates..
        /// </summary>
        public static string GetProfessionalTitles_Description {
            get {
                return ResourceManager.GetString("GetProfessionalTitles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownik tytułów zawodowych / Professional titles dictionary.
        /// </summary>
        public static string GetProfessionalTitles_Summary {
            get {
                return ResourceManager.GetString("GetProfessionalTitles_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobiera klasyfikację typów dla instytucji o profilu naukowym. / Retrieves the classification of types for scientific institutions..
        /// </summary>
        public static string GetScientificInstitutionTypes_Description {
            get {
                return ResourceManager.GetString("GetScientificInstitutionTypes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownik typów instytucji naukowych / Scientific institution types dictionary.
        /// </summary>
        public static string GetScientificInstitutionTypes_Summary {
            get {
                return ResourceManager.GetString("GetScientificInstitutionTypes_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobiera listę typów uczelni (np. publiczna, niepubliczna, kościelna). / Retrieves the list of university types (e.g., public, non-public, ecclesiastical)..
        /// </summary>
        public static string GetUniversityTypes_Description {
            get {
                return ResourceManager.GetString("GetUniversityTypes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słownik typów uczelni / University types dictionary.
        /// </summary>
        public static string GetUniversityTypes_Summary {
            get {
                return ResourceManager.GetString("GetUniversityTypes_Summary", resourceCulture);
            }
        }
    }
}
