//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUS.REGON {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUS.REGON.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucz nie moze byc pusta wrtościa.
        /// </summary>
        internal static string KeyErrorMessageEmpty {
            get {
                return ResourceManager.GetString("KeyErrorMessageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucz jest niepoprawny.
        /// </summary>
        internal static string KeyErrorMessageInvalid {
            get {
                return ResourceManager.GetString("KeyErrorMessageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konieczne jest pobranie i sprawdzenie kodu Captcha (metody PobierzCaptcha i SprawdzCaptcha). .
        /// </summary>
        internal static string KomunikatKod1 {
            get {
                return ResourceManager.GetString("KomunikatKod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do metody DaneSzukaj przekazano zbyt wiele identyfikatorów..
        /// </summary>
        internal static string KomunikatKod2 {
            get {
                return ResourceManager.GetString("KomunikatKod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono podmiotów..
        /// </summary>
        internal static string KomunikatKod4 {
            get {
                return ResourceManager.GetString("KomunikatKod4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak uprawnień do raportu..
        /// </summary>
        internal static string KomunikatKod5 {
            get {
                return ResourceManager.GetString("KomunikatKod5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak sesji. Sesja wygasła lub przekazano nieprawidłową wartość nagłówka sid..
        /// </summary>
        internal static string KomunikatKod7 {
            get {
                return ResourceManager.GetString("KomunikatKod7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usluga Niedostepna.
        /// </summary>
        internal static string StatusUslugi0 {
            get {
                return ResourceManager.GetString("StatusUslugi0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przerwa Techniczna.
        /// </summary>
        internal static string StatusUslugi2 {
            get {
                return ResourceManager.GetString("StatusUslugi2", resourceCulture);
            }
        }
    }
}
