//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUS.REGON {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUS.REGON.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucz nie moze byc pusta wrtościa.
        /// </summary>
        internal static string KeyErrorMessageEmpty {
            get {
                return ResourceManager.GetString("KeyErrorMessageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucz jest niepoprawny.
        /// </summary>
        internal static string KeyErrorMessageInvalid {
            get {
                return ResourceManager.GetString("KeyErrorMessageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konieczne jest pobranie i sprawdzenie kodu Captcha (metody PobierzCaptcha i SprawdzCaptcha). .
        /// </summary>
        internal static string KomunikatKod1 {
            get {
                return ResourceManager.GetString("KomunikatKod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do metody DaneSzukaj przekazano zbyt wiele identyfikatorów..
        /// </summary>
        internal static string KomunikatKod2 {
            get {
                return ResourceManager.GetString("KomunikatKod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono podmiotów..
        /// </summary>
        internal static string KomunikatKod4 {
            get {
                return ResourceManager.GetString("KomunikatKod4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak uprawnień do raportu..
        /// </summary>
        internal static string KomunikatKod5 {
            get {
                return ResourceManager.GetString("KomunikatKod5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak sesji. Sesja wygasła lub przekazano nieprawidłową wartość nagłówka sid..
        /// </summary>
        internal static string KomunikatKod7 {
            get {
                return ResourceManager.GetString("KomunikatKod7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport o miejscu prowadzenia działalności zarejestrowanej w CEIDG..
        /// </summary>
        internal static string PublDaneRaportDzialalnoscFizycznejCeidg {
            get {
                return ResourceManager.GetString("PublDaneRaportDzialalnoscFizycznejCeidg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport o miejscu prowadzenia pozostałej działalności..
        /// </summary>
        internal static string PublDaneRaportDzialalnoscFizycznejPozostala {
            get {
                return ResourceManager.GetString("PublDaneRaportDzialalnoscFizycznejPozostala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport o miejscu prowadzenia działalności rolniczej..
        /// </summary>
        internal static string PublDaneRaportDzialalnoscFizycznejRolnicza {
            get {
                return ResourceManager.GetString("PublDaneRaportDzialalnoscFizycznejRolnicza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja o miejscu prowadzenia działalności zlikwidowanej..
        /// </summary>
        internal static string PublDaneRaportDzialalnoscFizycznejWKrupgn {
            get {
                return ResourceManager.GetString("PublDaneRaportDzialalnoscFizycznejWKrupgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista prowadzonych przez jednostkę fizyczną działalności wg PKD..
        /// </summary>
        internal static string PublDaneRaportDzialalnosciFizycznej {
            get {
                return ResourceManager.GetString("PublDaneRaportDzialalnosciFizycznej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista prowadzonych przez jednostkę lokalną jednostki fizycznej działalności wg.PKD..
        /// </summary>
        internal static string PublDaneRaportDzialalnosciLokalnejFizycznej {
            get {
                return ResourceManager.GetString("PublDaneRaportDzialalnosciLokalnejFizycznej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista prowadzonych przez jednostkę lokalną jednostki prawnej działalności wg.PKD..
        /// </summary>
        internal static string PublDaneRaportDzialalnosciLokalnejPrawnej {
            get {
                return ResourceManager.GetString("PublDaneRaportDzialalnosciLokalnejPrawnej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista prowadzonych przez jednostkę prawną działalności wg PKD..
        /// </summary>
        internal static string PublDaneRaportDzialalnosciPrawnej {
            get {
                return ResourceManager.GetString("PublDaneRaportDzialalnosciPrawnej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport pełny o wybranej jednostce fizycznej. .
        /// </summary>
        internal static string PublDaneRaportFizycznaOsoba {
            get {
                return ResourceManager.GetString("PublDaneRaportFizycznaOsoba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport o jednostce lokalnej jednostki fizycznej.
        /// </summary>
        internal static string PublDaneRaportLokalnaFizycznej {
            get {
                return ResourceManager.GetString("PublDaneRaportLokalnaFizycznej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport o jednostce lokalnej jednostki prawnej..
        /// </summary>
        internal static string PublDaneRaportLokalnaPrawnej {
            get {
                return ResourceManager.GetString("PublDaneRaportLokalnaPrawnej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista jednostek lokalnych jednostki fizycznej..
        /// </summary>
        internal static string PublDaneRaportLokalneFizycznej {
            get {
                return ResourceManager.GetString("PublDaneRaportLokalneFizycznej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista jednostek lokalnych jednostki prawnej..
        /// </summary>
        internal static string PublDaneRaportLokalnePrawnej {
            get {
                return ResourceManager.GetString("PublDaneRaportLokalnePrawnej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport o jednostce prawnej..
        /// </summary>
        internal static string PublDaneRaportPrawna {
            get {
                return ResourceManager.GetString("PublDaneRaportPrawna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacja o typie jednostki..
        /// </summary>
        internal static string PublDaneRaportTypJednostki {
            get {
                return ResourceManager.GetString("PublDaneRaportTypJednostki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista wspólników spółki cywilnej..
        /// </summary>
        internal static string PublDaneRaportWspolnicyPrawnej {
            get {
                return ResourceManager.GetString("PublDaneRaportWspolnicyPrawnej", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usluga Niedostepna..
        /// </summary>
        internal static string StatusUslugi0 {
            get {
                return ResourceManager.GetString("StatusUslugi0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usluga Dostepna..
        /// </summary>
        internal static string StatusUslugi1 {
            get {
                return ResourceManager.GetString("StatusUslugi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przerwa Techniczna..
        /// </summary>
        internal static string StatusUslugi2 {
            get {
                return ResourceManager.GetString("StatusUslugi2", resourceCulture);
            }
        }
    }
}
