<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>Nullable</WarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Diploma.Domain\Diploma.Domain.csproj" />
		<ProjectReference Include="..\Diploma.Models\Diploma.Models.csproj" />
		<ProjectReference Include="..\Diploma.Shared\Diploma.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Projects\Queries\" />
	</ItemGroup>
	
</Project>
